### ISSUE TITLE
Typo dans la description du forum

### ISSUE THREAD

**Issue by MrBrownFR** [prepas-mp2i/prepas-mp2i.fr#39]
## Quoi ?

Comme noté par Younes (Fairy_Demon#6102 sur Discord), il y a une erreur dans le post pour le forum 2023. Actuellement, le texte est

> Cette édition est particulière, car elle _accueileura_ non seulement des _étduiants_ en MP2I mais aussi en deuxième année: MPI !

mais devrait être

> Cette édition est particulière, car elle __accueilera__ non seulement des __étudiants__ en MP2I mais aussi en deuxième année: MPI !

Ca vaut pas le coup d'ouvrir une PR juste pour ça donc je le fous là :)

**Comment by ajayat** [comment]
Bien vu, merci ! Très bonne idée par ailleurs de faire une issue.
Corrigé dans #15ccb6f
