### ISSUE TITLE
La carte des CPGE MP2I/MPI n'est plus à jour

### ISSUE THREAD

**Issue by Triw-12** [prepas-mp2i/prepas-mp2i.fr#61]
Sur https://prepas-mp2i.fr/filiere/#les-pr%C3%A9pas-mp2i-en-france, la carte présente encore les lycées qui vont ouvrir en 2023, or ces lycées ont déjà ouvert.
Je pense qu'il faudrait donc modifier la carte l'actualiser à cette année, avec par exemple, les prépas qui vont ouvrir cette année.

**Comment by KeyKatyu** [comment]
Bonjour,
Des nouvelles concernant la MAJ de cette carte ? Qui possède les droits ?

Merci.
